"""Generate plugin reference documentation from registered plugins.

Called at build time by the custom ``build_py`` command to produce a
markdown document that ships with the installed package under
``for_agents/preprocessing/plugins.md``.
"""

from __future__ import annotations

from databricks_agent_notebooks.preprocessing.engine import _BUILTIN_PLUGINS


def generate_plugin_docs() -> str:
    """Return a complete markdown document describing all built-in plugins."""
    lines: list[str] = [
        "<!-- AUTO-GENERATED by _build.py -- do not edit manually -->",
        "",
        "# Preprocessing Plugins",
        "",
        "Built-in plugins available in preprocessing directives.",
        "",
        "Directive syntax: `{! plugin_name(\"args\") !}`",
        "",
    ]

    for plugin_cls in _BUILTIN_PLUGINS:
        meta = plugin_cls.plugin_metadata()
        lines.append(f"## `{meta.name}`")
        lines.append("")
        lines.append(meta.description)
        lines.append("")
        if meta.markdown_docs:
            lines.append(meta.markdown_docs.strip())
            lines.append("")

    return "\n".join(lines) + "\n"
